[app]
name = "simprint-server"
port = 40041
secret = "Nuexz9Y2hRc5Z6HK7Atb"
prefix = "/api/v1"
encrypt_secret_location = "./assets/secret"
route_whitelists = [
    "POST+/api/v1/users/login",
    "POST+/api/v1/users/register",
    "POST+/api/v1/users/register-send-code",
    "POST+/api/v1/users/reset-password",
    "POST+/api/v1/users/reset-password-send-code",
    "POST+/api/v1/users/refresh-credentials",
    "GET+/api/v1/secret/public/key",
    "GET+/api/v1/time/now",
    "POST+/api/v1/versions/check"
]
referral_link_prefix = "https://www.simprint.app/download"

[database]
url = "postgres://simprint:simprint-postgres-password@postgres:5432/simprintdb"
max_connections = 25
min_connections = 5
max_lifetime = 3000
acquire_timeout = 30
idle_timeout = 600

[redis]
url = "redis://redis:6379?protocol=resp3"

[storage]
endpoint = "https://example.invalid"
public_base_url = "https://pub-39307a5e69c74324855a762027cbf9bf.r2.dev"
access_key = "disabled"
secret_access_key = "disabled"
bucket = "simprint-client"
avatar_root = "avatars"
extension_root = "extensions"
version_root = "versions"

[smtp]
smtp_server = "mailpit:1025"
smtp_username = ""
smtp_password = ""

[workspace_quota]
[workspace_quota.default]
max_environments = 99999
max_team_members = 99999
max_proxies = 99999
max_rpa_tasks = 99999
